const express = require('express');
const multer = require('multer');
const pageController = require('../controllers/Page.controller');
const rateLimitLogin = require('../middleware/rateLimit');
const { exigirRol, exigirSesion } = require('../middleware/webAuth');
const asyncHandler = require('../middleware/asyncHandler');

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });

router.get('/', (req, res) => res.render('publicos/index', { layout: false, active: 'inicio' }));
router.get('/login', (req, res) => pageController.renderLogin(req, res));
router.post('/login', rateLimitLogin, asyncHandler(pageController.login));
router.get('/registro', (req, res) => res.render('publicos/registro', { layout: false, proximo: req.query.next || '' }));
router.post('/registro', asyncHandler(pageController.registro));
router.get('/logout', pageController.logout);
router.get('/ayuda', (req, res) => res.render('publicos/ayuda', { layout: false }));
router.post('/ayuda', asyncHandler(pageController.ayuda));
router.get('/recuperar-password', (req, res) => res.render('publicos/recuperar_password', { layout: 'layouts/base', title: 'Recuperar contraseña', enviado: false }));
router.post('/recuperar-password', asyncHandler(pageController.solicitarRecuperacion));
router.get('/restablecer-password/:token', asyncHandler(pageController.renderReset));
router.post('/restablecer-password/:token', asyncHandler(pageController.restablecerPassword));
router.get('/como-funciona', (req, res) => res.render('publicos/como_funciona', { layout: 'layouts/base', title: '¿Cómo funciona?' }));
router.get('/sobre-nosotros', (req, res) => res.render('publicos/sobre_nosotros', { layout: 'layouts/base', title: 'Sobre nosotros' }));

router.get('/tienda', asyncHandler(pageController.tienda));
router.get('/servicios', pageController.servicios);
router.get('/peluquerias', asyncHandler(pageController.peluquerias));
router.get('/reservar-cita', exigirSesion, asyncHandler(pageController.reservarCita));
router.post('/pre-confirmar', exigirSesion, asyncHandler(pageController.preConfirmar));
router.post('/confirmar-reserva', exigirSesion, asyncHandler(pageController.confirmarReserva));
router.get('/perfil', exigirSesion, asyncHandler(pageController.perfil));
router.post('/perfil', exigirSesion, upload.single('foto'), asyncHandler(pageController.actualizarPerfil));
router.get('/notificaciones', exigirSesion, (req, res) => res.render('usuarios/usuario_notificaciones', { layout: false, notificaciones: [] }));
router.post('/notificaciones/leidas', exigirSesion, (req, res) => res.redirect('/notificaciones'));
router.get('/cambiar-password', exigirSesion, asyncHandler(pageController.cambiarPassword));
router.post('/cambiar-password', exigirSesion, asyncHandler(pageController.cambiarPassword));
router.get('/editar-reserva/:id', exigirSesion, asyncHandler(pageController.editarReserva));
router.post('/editar-reserva/:id', exigirSesion, asyncHandler(pageController.actualizarReserva));
router.post('/cancelar-reserva/:id', exigirSesion, asyncHandler(pageController.cancelarReserva));
router.post('/calificar/:id', exigirSesion, asyncHandler(pageController.calificar));
router.post('/confirmar-cita/:id', exigirSesion, asyncHandler(pageController.confirmarCita));

router.get('/carrito', asyncHandler(pageController.verCarrito));
router.post('/carrito/agregar/:id', asyncHandler(pageController.agregarCarrito));
router.post('/carrito/actualizar/:id', asyncHandler(pageController.actualizarCarrito));
router.post('/carrito/eliminar/:id', asyncHandler(pageController.eliminarCarrito));
router.get('/carrito/finalizar', exigirSesion, asyncHandler(pageController.finalizarCompra));
router.post('/carrito/finalizar', exigirSesion, asyncHandler(pageController.finalizarCompra));
router.get('/pedido-exitoso/:id', exigirSesion, asyncHandler(pageController.pedidoExitoso));

router.get('/barbero', exigirRol('Barbero', 'Admin'), asyncHandler(pageController.barberoDashboard));
router.get('/barbero/perfil', exigirRol('Barbero', 'Admin'), asyncHandler(pageController.barberoPerfil));
router.post('/barbero/perfil', exigirRol('Barbero', 'Admin'), upload.single('foto'), asyncHandler(pageController.actualizarPerfil));
router.get('/barbero/notificaciones', exigirRol('Barbero', 'Admin'), (req, res) => res.render('peluqueros/peluquero_notificaciones', { layout: 'layouts/dashboard', notificaciones: [] }));
router.get('/barbero/nueva-cita', exigirRol('Barbero', 'Admin'), asyncHandler(pageController.barberoNuevaCita));
router.post('/barbero/nueva-cita', exigirRol('Barbero', 'Admin'), asyncHandler(pageController.barberoGuardarCita));
router.post('/barbero/citas/:id/estado', exigirRol('Barbero', 'Admin'), asyncHandler(pageController.barberoEstadoCita));

router.get('/admin', exigirRol('Admin'), asyncHandler(pageController.adminDashboard));
router.get('/admin/perfil', exigirRol('Admin'), (req, res) => res.redirect('/perfil'));
router.get('/admin/usuarios', exigirRol('Admin'), asyncHandler(pageController.adminUsuarios));
router.get('/admin/usuarios/nuevo', exigirRol('Admin'), asyncHandler(pageController.adminFormularioUsuario));
router.post('/admin/usuarios/nuevo', exigirRol('Admin'), upload.single('foto'), asyncHandler(pageController.adminGuardarUsuario));
router.get('/admin/usuarios/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminFormularioUsuario));
router.post('/admin/usuarios/:id/editar', exigirRol('Admin'), upload.single('foto'), asyncHandler(pageController.adminGuardarUsuario));
router.post('/admin/usuarios/:id/suspender', exigirRol('Admin'), asyncHandler(pageController.adminSuspenderUsuario));
router.get('/admin/peluqueros', exigirRol('Admin'), asyncHandler(pageController.adminPeluqueros));
router.get('/admin/peluqueros/nuevo', exigirRol('Admin'), asyncHandler(pageController.adminFormularioPeluquero));
router.post('/admin/peluqueros/nuevo', exigirRol('Admin'), upload.single('foto'), asyncHandler(pageController.adminGuardarPeluquero));
router.get('/admin/peluqueros/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminFormularioPeluquero));
router.post('/admin/peluqueros/:id/editar', exigirRol('Admin'), upload.single('foto'), asyncHandler(pageController.adminGuardarPeluquero));
router.post('/admin/peluqueros/:id/suspender', exigirRol('Admin'), asyncHandler(pageController.adminSuspenderUsuario));
router.get('/admin/reservas', exigirRol('Admin'), asyncHandler(pageController.adminReservas));
router.get('/admin/reservas/nueva', exigirRol('Admin'), asyncHandler(pageController.adminFormularioReserva));
router.post('/admin/reservas/nueva', exigirRol('Admin'), asyncHandler(pageController.adminGuardarReserva));
router.get('/admin/reservas/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminFormularioReserva));
router.post('/admin/reservas/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminGuardarReserva));
router.post('/admin/reservas/:id/cancelar', exigirRol('Admin'), asyncHandler(pageController.adminCancelarReserva));
router.get('/admin/peluquerias', exigirRol('Admin'), asyncHandler(pageController.adminPeluquerias));
router.get('/admin/peluquerias/nueva', exigirRol('Admin'), asyncHandler(pageController.adminFormularioPeluqueria));
router.post('/admin/peluquerias/nueva', exigirRol('Admin'), asyncHandler(pageController.adminGuardarPeluqueria));
router.get('/admin/peluquerias/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminFormularioPeluqueria));
router.post('/admin/peluquerias/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminGuardarPeluqueria));
router.post('/admin/peluquerias/:id/eliminar', exigirRol('Admin'), asyncHandler(pageController.adminEliminarPeluqueria));
router.get('/admin/productos', exigirRol('Admin'), asyncHandler(pageController.adminProductos));
router.get('/admin/productos/nuevo', exigirRol('Admin'), asyncHandler(pageController.adminFormularioProducto));
router.post('/admin/productos/nuevo', exigirRol('Admin'), asyncHandler(pageController.adminGuardarProducto));
router.get('/admin/productos/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminFormularioProducto));
router.post('/admin/productos/:id/editar', exigirRol('Admin'), asyncHandler(pageController.adminGuardarProducto));
router.post('/admin/productos/:id/eliminar', exigirRol('Admin'), asyncHandler(pageController.adminEliminarProducto));
router.get('/admin/horarios', exigirRol('Admin'), asyncHandler(pageController.adminHorarios));
router.post('/admin/horarios', exigirRol('Admin'), asyncHandler((req, res) => req.body.accion === 'crear_bloqueo' ? pageController.adminCrearBloqueo(req, res) : pageController.adminGuardarHorarios(req, res)));
router.post('/admin/horarios/bloqueos/:id/eliminar', exigirRol('Admin'), asyncHandler(pageController.adminEliminarBloqueo));
router.get('/admin/mensajes', exigirRol('Admin'), asyncHandler(pageController.adminMensajes));
router.get('/admin/notificaciones', exigirRol('Admin'), (req, res) => res.render('administrador/admin_notificaciones', { layout: 'layouts/dashboard', notificaciones: [] }));
router.get('/admin/ingresos', exigirRol('Admin'), asyncHandler(pageController.adminIngresos));

module.exports = router;
